INFO 2022-01-04 12:01:19 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\botocore\credentials.py load 1224 credentials 16124 15536 Found credentials in shared credentials file: ~/.aws/credentials
ERROR 2022-01-04 12:01:20 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\django\utils\log.py log_response 224 log 16124 15536 Internal Server Error: /api/v1/component/data-request-view
ERROR 2022-01-04 12:01:20 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\django\utils\log.py log_response 224 log 16124 15536 Internal Server Error: /api/v1/component/pipeline-state-view
INFO 2022-01-04 16:33:52 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\botocore\credentials.py load 1224 credentials 16320 12308 Found credentials in shared credentials file: ~/.aws/credentials
ERROR 2022-01-04 16:33:52 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\django\utils\log.py log_response 224 log 16320 12308 Internal Server Error: /api/v1/component/data-request-view
ERROR 2022-01-04 16:33:53 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\django\utils\log.py log_response 224 log 16320 12308 Internal Server Error: /api/v1/component/pipeline-state-view
INFO 2022-01-04 16:45:45 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\botocore\credentials.py load 1224 credentials 10512 8324 Found credentials in shared credentials file: ~/.aws/credentials
ERROR 2022-01-04 16:45:46 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\django\utils\log.py log_response 224 log 10512 8324 Internal Server Error: /api/v1/component/data-request-view
ERROR 2022-01-04 16:45:46 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\django\utils\log.py log_response 224 log 10512 8324 Internal Server Error: /api/v1/component/pipeline-state-view
INFO 2022-01-05 13:11:42 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\botocore\credentials.py load 1224 credentials 9120 12272 Found credentials in shared credentials file: ~/.aws/credentials
ERROR 2022-01-05 13:11:44 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\django\utils\log.py log_response 224 log 9120 12272 Internal Server Error: /api/v1/component/data-request-view
ERROR 2022-01-05 13:11:44 C:\Users\ethzhu\PycharmProjects\Environments\django_env\lib\site-packages\django\utils\log.py log_response 224 log 9120 12272 Internal Server Error: /api/v1/component/pipeline-state-view
